#ejercicio 1
print('por favor ingresar nombres,apellidos,edad,direccion,numero de telefono y genero')
nombres= input('nombre\n')
apellidos= input('apellidos\n')
edad= input('edad\n')
direccion= input('direccion\n')
telefono= input('telefono\n')
genero= input('genero\n')
print('Datos ingresados')
print('Nombres: ', nombres)
print('Apellidos: ',apellidos)
print('Edad: ',edad)
print('Direccion: ',direccion)
print('Telefono: ',telefono)
print('Genero: ',genero)
